# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - beatsaboutFEapp

on:
  push:
    branches:
      - Catherine
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://p2beatsahoy.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3c1b4796c1ab41d797ccfcb69c92e42e }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9446caacc17a4bb390d2e0f75b7e7bd3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: p2beatsahoy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3c1b4796c1ab41d797ccfcb69c92e42e }}/p2beatsahoy/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'beatsaboutFEapp'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_0e35000f9927482fac754507d7d2ba29 }}
        images: 'p2beatsahoy.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3c1b4796c1ab41d797ccfcb69c92e42e }}/p2beatsahoy/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'